### ISSUE TITLE
`zk-index-view-note` opens continuously new buffers

### ISSUE THREAD

**Issue by jgru** [localauthor/zk#3]
Dear Grant, 

I have an issue with `zk-index-view-note`. Opposed to your [video demo](https://www.youtube.com/watch?v=7qNT87dphiA) `zk-index-view-note` opens new buffers endlessly, when navigating with `n` or `p` and does not just update the last visited buffer. 
Do you have an idea, what might be the problem here? 

Best regards,
jgru

**Comment by localauthor** [comment]
I've just pushed some improvements to `zk-index-next-line` and `-previous-line`. Maybe you could test them out?

The video demo shows how the functions work from `emacs -Q`, meaning, without any additional configuration. So, can you reproduce this error from `emacs -Q', just to rule out it's an issue with your config?

**Comment by jgru** [comment]
Thanks for your replay and the improvements. 

I tested the behaviour of `zk-index-view-note` with `emacs -Q` and the below mentioned minimal config.
The behaviour is still the same, but once I press `C-x 1` in the `*zk-index*`-buffer and then press `v`,`n`,... `zk-index-view-note` behaves as it should. Do you have any idea, what might be wrong here? 

```
(defvar bootstrap-version)
(let ((bootstrap-file
	   (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	  (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
	(with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
	  (goto-char (point-max))
	  (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil)
(straight-use-package 'use-package)

(use-package vertico
  :straight t
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))

(use-package orderless
  :straight t
  :after vertico
  :custom (completion-styles '(orderless)))

(use-package consult
  :straight t
  :after vertico
  :hook (completion-list-mode . consult-preview-at-point-mode))

(use-package zk
  ;;:straight (:host github :repo "localauthor/zk"  :files ("zk.el" "zk-consult.el" "zk-index.el"))
  :straight nil
  :load-path "~/zk-lisp/zk"
  :init
  (require 'zk)
  (require 'zk-consult)
  (require 'zk-index)
  :custom
  ;; Basic setup
  (zk-directory "/tmp/zk")
  (zk-file-extension "org")
  ;; Presents a list of current notes
  (zk-current-notes #'zk-consult-current-notes)
  :hook
  (add-hook 'completion-at-point-functions #'zk-completion-at-point 'append))
```

**Comment by jgru** [comment]
I had a closer look at it and think, that the following function definition works better (at least for me):

```elisp
(defvar zk-index-view-buf "*ZK-View*")

(defun zk-index-view-note ()
  "View note in view mode."
  (interactive)
  ;; Kill old viewing buffer
  (if (get-buffer zk-index-view-buf)
      (kill-buffer zk-index-view-buf))

  (delete-other-windows)
  ;; Open the note for viewing
  (push-button nil t)
  (rename-buffer zk-index-view-buf)
  (view-mode)
  ;; Focus *ZK-Index* again
  (set-window-buffer (other-window -1)  "*ZK-Index*")
  (switch-to-buffer "*ZK-Index*")
  )
```

**Comment by localauthor** [comment]
Sorry, but I'm still not able to reproduce this issue. The follow works as expected. The only difference is that in the above you are loading `zk` locally, not directly from the repo. Maybe that's the issue?

Also, is the variable `zk-index-auto-scroll` set to t?

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
	   (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	  (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
	(with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
	  (goto-char (point-max))
	  (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil)
(straight-use-package 'use-package)

(use-package vertico
  :straight t
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))

(use-package orderless
  :straight t
  :after vertico
  :custom (completion-styles '(orderless)))

(use-package consult
  :straight t
  :after vertico
  :hook (completion-list-mode . consult-preview-at-point-mode))

(use-package zk
  :straight (:host github :repo "localauthor/zk"  :files ("zk.el" "zk-consult.el" "zk-index.el"))
  :init
  (require 'zk)
  (require 'zk-consult)
  (require 'zk-index)
  :custom
  ;; Basic setup
  (zk-directory "~/tmp/zk-test")
  (zk-file-extension "org")
  ;; Presents a list of current notes
  (zk-current-notes #'zk-consult-current-notes)
  :hook
  (add-hook 'completion-at-point-functions #'zk-completion-at-point 'append))
```

**Comment by jgru** [comment]
> Sorry, but I'm still not able to reproduce this issue. The follow works as expected. The only difference is that in the above you are loading `zk` locally, not directly from the repo. Maybe that's the issue?
> 
> Also, is the variable `zk-index-auto-scroll` set to t?
> 

Thank you for posting the config. I tested it via `emacs -Q` and experience the same problems. `zk-index-auto-scroll` is set to `t`. 
The issue arises both using the Github-repo and the version on melpa. I'm running Emacs 27.1 on Debian. The implementation in #4 works however.

**Comment by jgru** [comment]
Since #4 is insufficient, do you have an idea on how to tackle this (rather problematic) issue? I can't track it down. Do you have any idea how to triage this? Again, using `emacs -Q` with the minimal config below leads to this issue as well.

**Comment by localauthor** [comment]
Seems we're at a bit of an impasse, because I can't figure out how to reproduce the issue.

Now that `zk-index` is on melpa, I tried it with an even more minimal config and still works as expected:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)

(package-install 'zk-index)

(setq zk-directory "~/tmp/zk-test"
      zk-file-extension "org")
```

GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0)

**Comment by jgru** [comment]
Unfortunately, I encounter the same issue with the minimal config above.
Running GNU Emacs 27.1 on Debian 12, compiled with the standard build options

```
emacs -nw -q --batch --eval '(message system-configuration-options)'

--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-cairo --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars ’CFLAGS=-g -O2 -ffile-prefix-map=/build/emacs-fQHadv/emacs-27.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall’ ’CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2’ LDFLAGS=-Wl,-z,relro
```

**Comment by jgru** [comment]
I think that it has something to do how buttons are created and which default action is linked to at that point. 
Could you clarify, how buttons are created for `zk-index`, since I didn't find an explicit `make-button`-call where I could experiment with the given action. 

Thanks!

**Comment by localauthor** [comment]
You'll find `insert-text-button` in the function `zk-index--insert`

**Comment by jgru** [comment]
It seems like this issue has something to do with org-mode.
Using the code in https://github.com/localauthor/zk/pull/8 solves the issue, didn't bother to figure it out in detail.

**Comment by jgru** [comment]
This issue _only_ arises when Emacs is run on a rather large screen (27", 2560x1140). 
I think, this is neither related to with `org`-style links  nor the `make-button`-behaviour but solely to Emacs policy larger displays.
Given that information, do you have any idea how this issue could be tackled, @localauthor ?

**Comment by localauthor** [comment]
That's a really helpful lead! Could you try the following functions and report back?

```elisp
(defun zk-index-next-line ()
  "Move to next line.
If 'zk-index-auto-scroll' is non-nil, show note in other window."
  (interactive)
  (let ((buffer (current-buffer))
        (split-width-threshold nil))
    (if (save-excursion
          (forward-line)
          (and zk-index-auto-scroll
               (zk-index--button-at-point-p)))
        (progn
          (other-window 1)
          (when (and (zk-file-p)
                     view-mode
                     (not (buffer-modified-p)))
            (kill-buffer))
          (if (get-buffer-window buffer)
              (other-window -1)
            (select-window (get-buffer-window buffer)))
          (forward-line)
          (unless (looking-at-p "[[:space:]]*$")
            (zk-index-view-note)))
      (forward-line))))

(defun zk-index-previous-line ()
  "Move to previous line.
If 'zk-index-auto-scroll' is non-nil, show note in other window."
  (interactive)
  (let ((buffer (current-buffer))
        (split-width-threshold nil))
  (if (save-excursion
          (forward-line -1)
          (and zk-index-auto-scroll
               (zk-index--button-at-point-p)))
      (progn
        (other-window 1)
        (when (and (zk-file-p)
                   view-mode
                   (not (buffer-modified-p)))
          (kill-buffer))
        (if (get-buffer-window buffer)
            (other-window -1)
          (select-window (get-buffer-window buffer)))
        (forward-line -1)
        (unless (looking-at-p "[[:space:]]*$")
          (zk-index-view-note)))
    (forward-line -1))))
```

**Comment by localauthor** [comment]
I should ask, does the behavior change when you change the size of the emacs frame? Are you using emacs in fullscreen?
